spring:
  profiles:
    active:
      - db
  datasource:
    url: jdbc:mysql://54.234.147.205:3306/project1?createDatabaseIfNotExist=true&autoReconnect=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    generate-ddl: true
  servlet:
    multipart:
      max-file-size: 10MB
jwt:
  header: Authorization
  secret: "&E)H@McQfTjWmZq4t7w!z%C*F-JaNdRgUkXp2r5u8x/A?D(G+KbPeShVmYq3t6v9"
  expiration: 604800
  route:
    authentication:
      path: auth
      refresh: refresh
